apiVersion: v1
kind: ConfigMap
metadata:
  name: openssh-server-custom-init
data:
  enable-port-forwarding.sh: |-
    #!/bin/bash
    set -e
    sed -i 's/#AllowAgentForwarding yes/AllowAgentForwarding yes/g' /etc/ssh/sshd_config
    sed -i 's/AllowTcpForwarding no/AllowTcpForwarding yes/g' /etc/ssh/sshd_config
    sed -i 's/GatewayPorts no/GatewayPorts yes/g' /etc/ssh/sshd_config
    sed -i 's/X11Forwarding no/X11Forwarding yes/g' /etc/ssh/sshd_config