apiVersion: v1
data:
  PUBLIC_KEY: c3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBQkpRQUFBUUVBaDAzYTRPd0dFMklzeTdxUXR6TkNOU05tV042U0ZTMEdXWkFmSzRURzc2ZlhMMm16N2gzMDFnc1ZDM0R2NC9Sa3NYZkdlQmtRSjJtN2pDdlBxRVBJbjgrZkllTU9lS2pvRkZLTUZycGV0eWxKMzVmSEpkNTFWR2thN1hsN1hJcVhYSmVTbElCTGpDbDJBekl2bEhKcUVVdWI5aDlKWlA0UzJvMzhUTzhwVnZ0N1R0VDg1T0VDOE5Ya2UyRzUzRWVFdVFQRVplQjV0MW5WSlhlWUlnUXFyOWs5QS9YYnEvalV1NlNmeWxnVVNXZUZ4RWhLZVhMeHhLbEZZbFVVZzRySGo2THYzMTArL29keGZpMmJYWThlNDZUc3NJbGdUNkN1VjVBME5vSFRISlpxYmJTdWMyeEtyNmVmZFBDeDlHc3Z0TVBPemE4RHhUem8ydDhJUGpXRWtRPT0gbGludXhzZXJ2ZXIuaW9Ab3BlbnNzaC1zZXJ2ZXI=
kind: Secret
metadata:
  name: openssh-server-env