apiVersion: v1
kind: Service
metadata:
  labels:
    app: openssh-server
  name: openssh-server
spec:
  ports:
  - name: 2222-2222
    port: 2222
    protocol: TCP
    targetPort: 2222
  selector:
    app: openssh-server
  type: ClusterIP