---
apiVersion: v1
kind: Namespace
metadata:
  name: openssh
---
apiVersion: v1
data:
  PUBLIC_KEY: c3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBQkpRQUFBUUVBelVqL2VGSlpYK2FZTUt6SjJhNi93d1FJZnRMdlc4UVFCUWtzNDVBcXFBcEduQkNyRmdocGMrK1QzcU1YaFJMVFloZW04dTBrMC9iTy9CTzVKTUZsaEhRUjA5U2Y1VFNneVIzVEVraThLaWNpRVFxZ1pNeklqRjNHWWhZVXlFRlR2Zk1IbW1Ib293c2E3OUpkNGh5MGMyU2VnTGtqeDk5QlpVRklyUnVuKzN1TFJsaW5jVGttZkY0SEdGTjVNd0w2Z2QrUDRDT3BEdGgxQlJUYklaQmI1ZDBYSFhqQnZLNDNnekdndGtiQjR1eThzNHJ4MGRUWlp4WTgyVVgySXZqWDdVejJvNVdQa1NXWjFKUk5IRkh0dEZkSFZxeFhNWGhjWGlzVGt6cVhEY2I5SDlRc3Q5MXRNQVUyeUhTRUhTVDEwa3hNbDdQNzFNbzdKQk9iNzhiVXJ3PT0gbGludXhzZXJ2ZXIuaW9Ab3BlbnNzaA==
kind: Secret
metadata:
  name: openssh
  namespace: openssh
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openssh-init-config
  namespace: openssh
data:
  enable-port-forwarding.sh: |-
    #!/bin/bash
    set -e
    sed -i 's/#AllowAgentForwarding yes/AllowAgentForwarding yes/g' /etc/ssh/sshd_config
    sed -i 's/AllowTcpForwarding no/AllowTcpForwarding yes/g' /etc/ssh/sshd_config
    sed -i 's/GatewayPorts no/GatewayPorts yes/g' /etc/ssh/sshd_config
    sed -i 's/X11Forwarding no/X11Forwarding yes/g' /etc/ssh/sshd_config
---
apiVersion: v1
data:
  PGID: "1000"
  PUID: "1000"
  SUDO_ACCESS: "true"
  TZ: Europe/London
kind: ConfigMap
metadata:
  name: openssh
  namespace: openssh
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: openssh-volume
spec:
  storageClassName: manual
  capacity:
    storage: 50Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/ssh/config"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openssh-claim
  namespace: openssh
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  storageClassName: manual
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openssh
  namespace: openssh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openssh
  template:
    metadata:
      labels:
        app: openssh
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: openssh
        - secretRef:
            name: openssh
        image: lscr.io/linuxserver/openssh-server
        imagePullPolicy: IfNotPresent
        name: openssh-server
        ports:
        - containerPort: 2222
          protocol: TCP
        volumeMounts:
        - mountPath: /config/custom-cont-init.d
          name: openssh-init-config
        - mountPath: /config
          name: default-config-volume
      volumes:
      - configMap:
          defaultMode: 420
          name: openssh-init-config
        name: openssh-init-config
      - name: default-config-volume
        persistentVolumeClaim:
          claimName: openssh-claim
---
apiVersion: v1
kind: Service
metadata:
  name: openssh-svc
  namespace: openssh
spec:
  ports:
  - name: 2222-2222
    port: 2222
    protocol: TCP
    targetPort: 2222
  selector:
    app: openssh-svc
  type: ClusterIP
---